lsi: true # Enable LSI for improved search capabilities
safe: true
source: .
incremental: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed # Add feed plugin for better content management
  - jekyll-seo-tag # Add SEO tags for better visibility

